sql:
  host: localhost
  user: root
  password: hopefullyNotPassword
  database: punishments
  port: 3306

chat-prefix: "&6&lHydra&f&l(Punishments) &e» &f"

categories:
  chat:
    icon: MATERIAL
    gui-name: "Chat Offenses"
    types:
      spam:
        icon: MATERIAL
        gui-name: "Temp Mute"
        allow-ban: true
        allow-perm-mute: true
        allow-ip-ban: false
        lengths:
          tempmute:
          - "1h0m0s"
          - "1h0m0s"
          - "1h0m0s"
          - "1h0m0s"
          tempban:
          - "1h0m0s"
          - "1h0m0s"
          - "1h0m0s"
          - "1h0m0s"

messages:
  staff: "You have %type% %player% for %category% - %subCat%"
  ingame: "%player% has been %type% for %category% - %subCat%"

  ban: "            &c&bPERMANENTLY BANNED\n
              You have been banned from HydraCraft\n
              Reason: %reason%\n\n

              Purchase an unban at\n
              https://store.hydracraft.net/category/1422152\n\n

              Do you feel this was a mistake?\n
              Appeal on the forums:\n
              http://hydracraft.net/forums"

  tempban: "        &c&bTEMPORARILY BANNED&r\n
              You have been banned from HydraCraft\n
              Reason: %reason%\n\n

              Ban expires in: %timeRemaining%\n\n

              Purchase an unban at\n
              https://store.hydracraft.net/category/1422152\n\n

              Do you feel this was a mistake?\n
              Appeal on the forums:\n
              http://hydracraft.net/forums"
  
  mute: "###################################################\n
                  You’ve been &c&bPERMANENTLY&r muted by %staff%\n
                  Reason: Character Spam\n\n

                  Get an unmute at\n
                  https://store.hydracraft.net/category/1422152\n
                  Contact support if you feel this was a mistake\n
                  hydracraft.net/forums/appeals\n
        ###################################################"

  tempmute: "###################################################\n
                 You’ve been muted for %time% by %staff%\n
                 Reason: Character Spam\n\n

                 Next Punishment: %next%\n
             ###################################################"

  kick: "You were kicked by %by% for %reason%%"
  
  warning: "You have been warned by %by% for %reason%"