debug: true

redis:
  host: localhost
  port: 6379

sql:
  host: localhost
  user: root
  password: password
  database: punishments
  port: 3306

record-expire-time: "7d"

chat-prefix: "&6&lHydra&f&l(Punishments) &e» &f"

categories:
  hacking:
    icon: DIAMOND_SWORD
    gui-name: "Hacking / Cheating"
    types:
      kill-aura:
        icon: WATER_BUCKET
        gui-name: "Kill Aura"
        punishments:
        - "tempban"
        - "ban"
        lengths:
          tempban:
          - "2h"
          - "12h"
          - "24h"

  chat:
    icon: BOOK_AND_QUILL
    gui-name: "Chat Offenses"
    types:
      spam:
        icon: PAPER
        gui-name: "Spam"
        punishments:
        - "warning"
        - "tempmute"
        - "mute"
        lengths:
          tempmute:
          - "30m"
          - "1h"
          - "12h"

messages:
  staff: "You have %type% %player% for %category% - %subCat%"
  ingame: "%player% has been %type% for %category% - %subCat%"

  ban: "&c&lPERMANENTLY BANNED\n
              You have been banned from HydraCraft\n
              Reason: %category% - %subCat%\n\n

              Purchase an unban at\n
              https://store.hydracraft.net/category/1422152\n\n

              Do you feel this was a mistake?\n
              Appeal on the forums:\n
              http://hydracraft.net/forums"

  ipban: "&c&lPERMANENTLY IP BANNED\n
              You have been IP Banned from HydraCraft\n
              Reason: %category% - %subCat%\n\n

              Do you feel this was a mistake?\n
              Appeal on the forums:\n
              http://hydracraft.net/forums"

  tempban: "&c&bTEMPORARILY BANNED&r\n
              You have been banned from HydraCraft\n
              Reason: %category% - %subCat%\n\n

              Ban expires in: %timeRemaining%\n\n

              Purchase an unban at\n
              https://store.hydracraft.net/category/1422152\n\n

              Do you feel this was a mistake?\n
              Appeal on the forums:\n
              http://hydracraft.net/forums"
  
  mute: "###################################################\n
                  You have been &c&bPERMANENTLY&r muted by %staff%\n
                  Reason: %category% - %subCat%\n\n

                  Get an unmute at\n
                  https://store.hydracraft.net/category/1422152\n
                  Contact support if you feel this was a mistake\n
                  hydracraft.net/forums/appeals\n
        ###################################################"

  tempmute: "###################################################\n
                 You have been muted for %timeRemaining% by %staff%\n
                 Reason: Reason: %category% - %subCat%\n\n

                 Next Punishment: %next%\n
             ###################################################"

  kick: "You were kicked by %staff% for Reason: %category% - %subCat%"
  
  warning: "You have been warned by %staff% Reason: %category% - %subCat%"